version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
            -
      - run:
          name: Run unit tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 app/tests.py

      - run:
          name: Run flake8
          command: |
            . venv/bin/activate
            flake8 --count app/

      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
